onboarding = false
[theme]
name = "catppuccin"

[theme.custom]
panel_bg = "#191925"
sidebar_bg = "#191925"
active_row_bg = "#202031"
selection_bg = "#302540"
surface0 = "#202031"
surface1 = "#302540"
surface_dim = "#191925"
overlay0 = "#5f6077"
overlay1 = "#797a96"
text = "#c8c9e5"
subtext0 = "#81849f"
mauve = "#c096ed"
green = "#a7eb9c"
yellow = "#f6dfa0"
red = "#fa7e9f"
blue = "#aeb9ff"
teal = "#71ddd6"
peach = "#e77b58"
accent = "#be97ed"

[keys]
prefix = "ctrl+a"
help = "prefix+?"
settings = "prefix+shift+s"
detach = ["prefix+d", "prefix+q"]
reload_config = "prefix+shift+r"
workspace_picker = "prefix+s"
goto = ["prefix+w", "prefix+g"]
navigate_workspace_up = ["up", "k", "ctrl+p"]
navigate_workspace_down = ["down", "j", "ctrl+n"]
rename_workspace = "prefix+$"
previous_workspace = "prefix+shift+p"
next_workspace = "prefix+shift+n"
new_tab = "prefix+c"
rename_tab = "prefix+comma"
previous_tab = "prefix+p"
next_tab = "prefix+n"
switch_tab = "prefix+1..9"
close_tab = "prefix+ampersand"
copy_mode = "prefix+["
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
split_vertical = ["prefix+v", "prefix+percent"]
split_horizontal = ["prefix+minus", "prefix+quote"]
close_pane = "prefix+x"
zoom = "prefix+z"
resize_mode = "prefix+r"
resize_pane_left = "ctrl+shift+alt+left"
resize_pane_down = "ctrl+shift+alt+down"
resize_pane_up = "ctrl+shift+alt+up"
resize_pane_right = "ctrl+shift+alt+right"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "$HOME/.local/bin/herdr-sessionizer"
description = "open project workspace"
width = "80%"
height = "80%"

[worktrees]
directory = "~/.herdr/worktrees"

[ui]
accent = "#be97ed"
tab_bar_position = "bottom"
pane_borders = true
pane_outer_borders = true
pane_gaps = false
show_agent_labels_on_pane_borders = true
window_title = "{workspace}: {tab}"
prompt_new_tab_name = false


[ui.sidebar.spaces]
row_gap = 1
rows = [
  ["state_icon", "workspace"],
  ["branch", "git_status"],
]

[ui.sidebar.agents]
row_gap = 1
rows = [
  ["state_icon", "workspace", "tab"],
  ["state_text", "agent"],
]
